TutionCloudWeb/Models/PostModel/Favourites.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TutionCloudWeb.Models.PostModel
{
    public class Favourites
    {
        public class WordList
        {
            public int index { get; set; }
            public long userId { get; set; }
            public string totalWordCount { get; set; }
            public string searchText { get; set; }
            public string sortBy { get; set; }
            public string sortOrder { get; set; }
        }
        public class WordClass
        {
            public long userId { get; set; }
            public string totalWordCount { get; set; }
        }
        public class WordListPagination
        {
            public int index { get; set; }
            public long userId { get; set; }
            public string totalWordCount { get; set; }
            public string searchText { get; set; }
            public string sortBy { get; set; }
            public string sortOrder { get; set; }
        }
    }
}

TutionCloudWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TutionCloudWeb.Controllers
{
    public class HomeController : PreLoginBaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult Wordutopia()
        {
         
            return View();
        }

        public ActionResult Quester()
        {
            return View();
        }

        public ActionResult Choicer()
        {
            return View();
        }

    }
}

TutionCloudWeb/Controllers/Wordutopia/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TutionCloudWeb.Manager.Wordutopia;
using TutionCloudWeb.Model.Wordutopia;

namespace TutionCloudWeb.Controllers.Wordutopia
{
    public class NotesController : Controller
    {
        NotesManager NotesManager = new NotesManager();
        /// <summary>
        /// Name : Notes
        /// CreateBy : SIBI
        /// CreateON : 14/03/2019
        /// UpdatedBy : non
        /// Details : non 
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> Notes()
        {
            Notes model = new Notes();
            model.userId = SessionModel.UserId; ;
            model = await NotesManager.Notes(model);
            return View(model);
        }
        /// <summary>
        /// Name : refreshUserNoteList
        /// CreateBy : SIBI
        /// CreateON : 15/03/2019
        /// UpdatedBy : non
        /// Details : non 
        /// </summary>
        /// <returns></returns>

        [HttpPost]
        public ActionResult refreshUserNoteList(Notes model)
        {
            return PartialView("~/Views/Notes/_pv_Wordutopia_Note_List.cshtml", model);
        }

        /// <summary>
        /// Name : refreshUserNoteListPagination
        /// CreateBy : SIBI
        /// CreateON : 15/03/2019
        /// UpdatedBy : non
        /// Details : non 
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult refreshUserNoteListPagination(Notes model)
        {
            return PartialView("~/Views/Notes/_pv_Wordutopia_Note_List_Pagination.cshtml", model);
        }

        /// <summary>
        /// Name : NoteCount
        /// CreateBy : SIBI
        /// CreateON : 15/03/2019
        /// UpdatedBy : non
        /// Details : non 
        /// </summary>
        /// <returns></returns>
        public string NoteCount(long userId, string searchText)
        {
            try
            {
                var count = NotesManager.NoteCount(userId,searchText);
                return count;
            }
            catch (Exception ex)
            {
                return "0";
            }
        }

        /// <summary>
        /// Name : deletNote
        /// CreateBy : SIBI
        /// CreateON : 15/03/2019
        /// UpdatedBy : non
        /// Details : non 
        /// </summary>
        /// <returns></returns>
        public object deletNote(string noteId)
        {
            bool status = false;
            string message = "failed";
            if (noteId != null && noteId != string.Empty)
            {
                Tuple<bool, string> result = NotesManager.deletNote(noteId);
                return Json(new { status = result.Item1, message = result.Item2 }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                status = false;
                message = "failed";
                return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
            }
        }
	}
}

TutionCloudWeb/Controllers/Wordutopia/OnlineCommunityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TutionCloudWeb.Manager.Wordutopia;
using TutionCloudWeb.Model.Wordutopia;
using TutionCloudWeb.Models.Database;

namespace TutionCloudWeb.Controllers.Wordutopia
{
    public class OnlineCommunityController : BaseController
    {
        protected TutionCloudEntities TutionCloudEntities = new TutionCloudEntities();
        OnlineCommunityManager OnlineCommunityManager = new OnlineCommunityManager();
        public ActionResult OnlineCommunity()
        {
            return View();
        }
        public ActionResult CreateaWordListToShare()
        {
            var model = new TutionCloudWeb.Models.PostModel.OnlineCommunity.WordClass();
            //OnlineCommunityModel model = new OnlineCommunityModel();
            model.userId = _User.UserId;
            model.totalWordCount = TutionCloudEntities.SP_FETCH_USER_TOTAL_WORD_COUNT(model.userId, string.Empty).FirstOrDefault().ToString();
            return View(model);
            
        }
        [HttpGet]
        public JsonResult GetAllUserLists()
        {
            CreateAWordListToShareModel model = new CreateAWordListToShareModel();
            var results = TutionCloudEntities.tUsers.Select(x => new {x.Username, x.UserId}).ToList();
            
            return Json(results, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult CreateaWordListToShareSendList(TutionCloudWeb.Models.PostModel.Word.AddFavouriteWord model)
        {
            var results = OnlineCommunityManager.SendLIsts(model);

            return Json(results,JsonRequestBehavior.AllowGet); 
        }

        public ActionResult WordListSharedwithMe()
        {
            var model = new TutionCloudWeb.Models.PostModel.OnlineCommunity.WordClass();            
            model.userId = _User.UserId;
            model.totalWordCount = TutionCloudEntities.SP_CreateAWordListToShare_COUNT(model.userId, string.Empty).FirstOrDefault().ToString();
            return View(model);
        }

        public ActionResult Save_CreateaWordListToShare(CreateAWordListToShareModel model)
        {
            return null;
        }

        public ActionResult WordListSharedbyMe()
        {
            return View();
        }
        
        public ActionResult CreateaNewTesttoShare()
        {
            return View();
        }
        public ActionResult ShareanArchivedTest()
        {
            return View();
        }
        public ActionResult TestSharedbyMe()
        {
            return View();
        }
        public ActionResult TestSharedWithMe()
        {
            return View();
        }
        public ActionResult ManageSharedTestStats()
        {
            return View();
        }
	}
}

TutionCloudWeb/Controllers/WordutopiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TutionCloudWeb.Models.Repository;

namespace TutionCloudWeb.Controllers
{
    public class WordutopiaController : BaseController
    {
        private userRepository _userRepo = new userRepository();
        //
        // GET: /Wordutopia/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Home()
        {
            return View();
        }

        public ActionResult Words()
        {
            var model = new TutionCloudWeb.Models.PostModel.Word.WordClass();
            model.userId = _User.UserId;
            model.totalWordCount = _context.SP_FETCH_USER_TOTAL_WORD_COUNT(model.userId, string.Empty).FirstOrDefault().ToString();
            return View(model);
        }

        public ActionResult CreateWord()
        {
            var model = new TutionCloudWeb.Models.PostModel.Word.AddWord();
            model.userId = _User.UserId;
            model.sharOnline = true;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult addword(TutionCloudWeb.Models.PostModel.Word.AddWord model)
        {
            bool status = true;
            string message = "success";
            if (ModelState.IsValid)
            {
                var result = _userRepo.addword(model);
                return Json(new { status = result.status, message = result.message }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                status = false;
                message = "failed";
                return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult refreshUserWordList(TutionCloudWeb.Models.PostModel.Word.WordList model)
        {
            return PartialView("~/Views/Wordutopia/_pv_Wordutopia_Word_List.cshtml", model);
        }

        [HttpPost]
        public ActionResult refreshUserWordListPagination(TutionCloudWeb.Models.PostModel.Word.WordListPagination model)
        {
            return PartialView("~/Views/Wordutopia/_pv_Wordutopia_Word_List_Pagination.cshtml", model);
        }

        public object deletWord(string wordId)
        {
            bool status = false;
            string message = "failed";
            if (wordId != null && wordId != string.Empty)
            {
                Tuple<bool, string> result = _userRepo.deletWord(wordId);
                return Json(new { status = result.Item1, message = result.Item2 }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                status = false;
                message = "failed";
                return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
            }
        }

        public string WordCount(long userId, string searchText)
        {
            try
            {
                var count = _context.SP_FETCH_USER_TOTAL_WORD_COUNT(userId, searchText ?? string.Empty).FirstOrDefault().ToString();
                return count;
            }
            catch (Exception ex)
            {
                return "0";
            }
        }


        public ActionResult Notes()
        {
            var model = new TutionCloudWeb.Models.PostModel.Note.NoteClass();
            model.userId = _User.UserId;
            model.totalNoteCount = _context.SP_FETCH_USER_TOTAL_NOTE_COUNT(model.userId, string.Empty).FirstOrDefault().ToString();
            return View(model);
        }

        [HttpPost]
        public ActionResult refreshUserNoteList(TutionCloudWeb.Models.PostModel.Note.NoteList model)
        {
            return PartialView("~/Views/Wordutopia/_pv_Wordutopia_Note_List.cshtml", model);
        }

        [HttpPost]
        public ActionResult refreshUserNoteListPagination(TutionCloudWeb.Models.PostModel.Note.NoteListPagination model)
        {
            return PartialView("~/Views/Wordutopia/_pv_Wordutopia_Note_List_Pagination.cshtml", model);
        }

        public string NoteCount(long userId, string searchText)
        {
            try
            {
                var count = _context.SP_FETCH_USER_TOTAL_NOTE_COUNT(userId, searchText ?? string.Empty).FirstOrDefault().ToString();
                return count;
            }
            catch (Exception ex)
            {
                return "0";
            }
        }

        public object deletNote(string noteId)
        {
            bool status = false;
            string message = "failed";
            if (noteId != null && noteId != string.Empty)
            {
                Tuple<bool, string> result = _userRepo.deletNote(noteId);
                return Json(new { status = result.Item1, message = result.Item2 }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                status = false;
                message = "failed";
                return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult CreateNote()
        {
            var model = new TutionCloudWeb.Models.PostModel.Note.AddNote();
            model.userId = _User.UserId;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult addnote(TutionCloudWeb.Models.PostModel.Note.AddNote model)
        {
            bool status = true;
            string message = "success";
            if (ModelState.IsValid)
            {
                var result = _userRepo.addnote(model);
                return Json(new { status = result.status, message = result.message }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                status = false;
                message = "failed";
                return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Favourites()
        {
            var model = new TutionCloudWeb.Models.PostModel.Favourites.WordClass();
            model.userId = _User.UserId;
            model.totalWordCount = _context.SP_FETCH_USER_TOTAL_FAVOURITE_WORD_COUNT(model.userId, string.Empty).FirstOrDefault().ToString();
            return View(model);
        }

        public ActionResult EditWord(string id)
        {
            byte[] b = Convert.FromBase64String(id);

            var strOriginal = System.Text.Encoding.UTF8.GetString(b);

            string[] values = strOriginal.Split('-');
            for (int i = 0; i < values.Length; i++)
            {
                values[i] = values[i].Trim();
            }

            var wordId = Convert.ToInt64(values[0]);
            var model = new TutionCloudWeb.Models.PostModel.Word.EditWord();
            model.redirectTo = values[1];
            model.mainPanelIndex = Convert.ToInt32(values[2]);
            model.userId = _User.UserId;
            model.wordId = wordId;

            var word = _context.SP_FETCH_WORD_BY_ID(wordId).ToList().Select(z => new TutionCloudWeb.Models.DataClass.SP_FETCH_WORD_BY_ID(z)).FirstOrDefault();
            if (word != null)
            {
                model.sharOnline = word.SHAREONLINE;
                model.definition = word.DEFINITION;
                model.hint = word.HINT;
                model.phrase = word.PHRASE;
                model.pronounciation = word.PRONOUNCIATION;
                model.word = word.WORD;
                return View(model);
            }
            else
            {
                //return HttpNotFound();
                return RedirectToAction("Words");
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult editword(TutionCloudWeb.Models.PostModel.Word.EditWord model)
        {
            bool status = true;
            string message = "success";
            if (ModelState.IsValid)
            {
                var result = _userRepo.editword(model);
                return Json(new { status = result.status, message = result.message }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                status = false;
                message = "failed";
                return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult EditNote(string id)
        {
            var noteId = Convert.ToInt64(id);
            var model = new TutionCloudWeb.Models.PostModel.Note.EditNote();
            model.userId = _User.UserId;
            model.noteId = noteId;

            var word = _context.SP_FETCH_NOTE_BY_ID(noteId).ToList().Select(z => new TutionCloudWeb.Models.DataClass.SP_FETCH_NOTE_BY_ID(z)).FirstOrDefault();
            if (word != null)
            {
                model.title = word.TITLE;
                model.description = word.DESCRIPTION;
                return View(model);
            }
            else
            {
                return RedirectToAction("Notes");
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult editnote(TutionCloudWeb.Models.PostModel.Note.EditNote model)
        {
            bool status = true;
            string message = "success";
            if (ModelState.IsValid)
            {
                var result = _userRepo.editnote(model);
                return Json(new { status = result.status, message = result.message }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                status = false;
                message = "failed";
                return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult MainPanel(string id)
        {
            byte[] b = Convert.FromBase64String(id);

TutionCloudWeb/Views/Wordutopia/CreateTest.cshtml
@model TutionCloudWeb.Models.PostModel.Exam.CreateTest
@{
    ViewBag.Title = "CreateTest";
    Layout = "~/Views/Shared/_Layout_Wordutopia_Home.cshtml";
}
<style>
    .field-validation-error {
        color: red;
    }
</style>
<section class="Crt_formt">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="Tst_head">
                    <h6>Create Test</h6>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="Crt_tst_fomt">
                    <div class="newdrpn">
                        <div class="dropdown">
                            <button type="button" class="btn btn-primary " data-toggle="dropdown">Task Dropdown List <img src="~/Content/img/rightarrow.png" /></button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" onclick="history.back()">Back</a>
                                @*<a class="dropdown-item" href="#">Create a Test Format </a>*@
                            </div>
                        </div>
                    </div>
                    <div class="Avg_scr">
                        <p>Average score to date: 87.2%</p>
                    </div>
                    <div class="outer_tst">
                        @using (Ajax.BeginForm("createtest", "Wordutopia", null, new AjaxOptions
        {
            HttpMethod = "POST",
            OnSuccess = "createtestSuccess",
            OnFailure = "createtestFailure",
        }, new { id = "tutioncloud-createtest" }))
                        {
                            @Html.ValidationSummary(true)
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(z => z.userId, new { Value = Model.userId })
                            @Html.HiddenFor(z => z.wordIds, new { Value = Model.wordIds })
                            <div class="test_form">
                                <h6>Test Details</h6>
                                <div class="form-group">
                                    <div class="form_al">
                                        <label>Test Title:</label>
                                        @*<input type="text" class="form-control" />*@
                                        @Html.TextBoxFor(m => m.title, new { autocomplete = "off", @class = "form-control" })
                                        @*@Html.ValidationMessageFor(model => model.title)*@
                                        <span id="error-title"style="display:none;" class="field-validation-error">required</span>
                                    </div>
                                </div>
                            </div>
                            <div class="test_frm">
                                <h6>Choose Test Format</h6>
                                <div class="form-group">
                                    <div class="form_al">
                                        <label>Overall Test Time (In Minutes):</label>
                                        @*<input type="text" class="form-control" />*@
                                        @Html.TextBoxFor(m => m.testTime, new { autocomplete = "off", @class = "form-control" })
                                        @*@Html.ValidationMessageFor(model => model.testTime)*@
                                        <span id="error-testTime" style="display:none;" class="field-validation-error">required</span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="form_al"style="text-align:center;font-weight:600;">
                                      OR
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="form_al">
                                        <label>Time per Word (In seconds):</label>
                                        @*<input type="text" class="form-control" />*@
                                        @Html.TextBoxFor(m => m.timePerWord, new { autocomplete = "off", @class = "form-control" })
                                        @*@Html.ValidationMessageFor(model => model.timePerWord)*@
                                        <span id="error-timePerWord" style="display:none;" class="field-validation-error">required</span>
                                    </div>
                                </div>

                            </div>
                            <div class="Bttn">
                                <button type="submit" style="display:none;" id="btn-create-test" class="btn tst_btn">Start Test</button>
                                <button type="button" id="btn-dummy-create-test" class="btn tst_btn">Start Test</button>
                            </div>
                        }
                    </div>
                </div>
                <div class="lowerNav">
                    <nav class="navbar navbar-expand-sm  justify-content-center">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a href="https://en.wikipedia.org/wiki/Main.page" target="_blank">Wikipedia</a>
                            </li>
                            <li class="nav-item">
                                <a href=" https://www.google.com/search?q=calculator" target="_blank">Calculator</a>
                            </li>
                            <li class="nav-item">
                                <a href="https://www.google.com/maps/" target="_blank">Maps</a>
                            </li>
                            <li class="nav-item">
                                <a href="https://www.google.com/search?ei=DyM3XNbMEdH6kwW-lpLgCA&q=google+currency+converter&oq=google+currency+converter&gs_l=psy-ab.3..35i39j0i7i30l2j0j0i7i30j0j0i7i30j0l3.211.5629..6378...0.0..0.282.1593.0j6j3......0....1..gws-wiz.......0i71j0i30j0i131i67j35i304i39.BbyIqE0P5UY" target="_blank">Currency Converter</a>
                            </li>
                            <li class="nav-item">
                                <a href="https://www.timeanddate.com/worldclock/full.html" target="_blank">World Clocks</a>
                            </li>
                            <li class="nav-item">
                                <a href="https://translate.google.com/" target="_blank">Translator</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>


<script>

    $(document).on('click', '#btn-dummy-create-test', function () {
        var title = $('#title').val();
        var testTime = $('#testTime').val();
        var timePerWord = $('#timePerWord').val();
        if (title != "" && title != null) {
            $('#error-title').hide();
            if ((testTime != "" && testTime != null) || (timePerWord != "" && timePerWord != null)) {
                $('#error-timePerWord').hide();
                $('#error-testTime').hide();
                $('#btn-create-test').trigger('click');
            }
            else {
                if ((testTime == "" || testTime == null) && (timePerWord == "" || timePerWord == null)) {
                    $('#error-timePerWord').show();
                    $('#error-testTime').show();
                }
            }
        }
        else {
            $('#error-title').show();
            if ((testTime != "" && testTime != null) || (timePerWord != "" && timePerWord != null)) {
                $('#error-timePerWord').hide();
                $('#error-testTime').hide();
            }
            else {
                if ((testTime == "" || testTime == null) && (timePerWord == "" || timePerWord == null)) {
                    $('#error-timePerWord').show();
                    $('#error-testTime').show();
                }
            }
        }
    });

</script>


<script>
    $(document).on('keypress', "#testTime , #timePerWord", function (e) {
        //if the letter is not digit then display error and don't type anything
        if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
            //display error message
            //$("#errmsg").html("Digits Only").show().fadeOut("slow");
            return false;
        }
    });
</script>

<script>
    function createtestFailure(data) {
        toastrError(data.message);
    }

    function createtestSuccess(data) {
        if (data.status) {
            toastrSuccess("Exam created")
            setTimeout(function () {
                var encodedString = btoa(data.id);
                window.location.href = "/Wordutopia/StartTest/" + encodedString;
            }, 400);
        }
        else {
            toastrError(data.message);
        }
    }

</script>

TutionCloudWeb/Views/Wordutopia/_pv_Test_Archives_List.cshtml
@model TutionCloudWeb.Models.PostModel.Exam.TestArchivesList
@{
    var testList = new TutionCloudWeb.Models.DataClass.WebService().getTestList(Model.userId, Model.index);
}


@if (testList.Count > 0)
{
    foreach (var test in testList)
    {
        byte[] byt12 = System.Text.Encoding.UTF8.GetBytes(test.EXAMID.ToString());

        var strModified12 = Convert.ToBase64String(byt12);

        <tr class="tr-word-row">
            <td><input class="ckb-word-item" data-examid="@test.EXAMID" type="checkbox"></td>
            <td>
                <strong>
                    <span class="spn-utcdate" style="display:none;" data-utctime="@test.CREATEDDATE.ToString()"></span>
                    <span class="spn-date"></span>
                    <span class="spc-Date"></span>
                    <span class="spn-time"></span>
                </strong>
            </td>
            <td>@test.SCORE %</td>
            <td>Self Gen</td>
            <td class="toggle_dropdown_cust">
                <div class="web-dsp">
                    <span class="edts"><a style="cursor:pointer;" href="/Wordutopia/TestSummary/@strModified12">View</a></span>
                    <span class="ck_brd">|</span>
                    <span class="edts"><a style="cursor:pointer;" href="/Wordutopia/ResitTest">Resit</a></span>
                    <span class="ck_brd">|</span>
                    <span class="edts"><a style="cursor:pointer;" class="test-delete" data-testid="@test.EXAMID">Delete</a></span>
                </div>
                <div class="togButns attachmts">
                    <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v"></i>
                    </button>
                    <div class="dropdown-menu labes" aria-labelledby="dropdownMenuButton">
                        <span class="edts"><a style="cursor:pointer;" href="/Wordutopia/TestSummary/@strModified12">View</a></span>
                        <span class="ck_brd">|</span>
                        <span class="edts"><a style="cursor:pointer;" href="/Wordutopia/ResitTest">Resit</a></span>
                        <span class="ck_brd">|</span>
                        <span class="edts"><a style="cursor:pointer;" class="test-delete" data-testid="@test.EXAMID">Delete</a></span>
                    </div>
                </div>
            </td>
        </tr>

    }
}
else
{
    <tr>
        <td colspan="5">No Test found</td>
    </tr>
}