TutionCloudWeb/Models/Database/CreateAWordListToShare.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutionCloudWeb.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateAWordListToShare
    {
        public decimal CreateAWordListToShareID { get; set; }
        public string SentUserID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string WordId { get; set; }
        public string Password { get; set; }
        public string TestID { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedOn { get; set; }
        public string Pronounciation { get; set; }
        public string Phrase { get; set; }
        public string Hint { get; set; }
        public string Definition { get; set; }
        public Nullable<bool> ShareOnline { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
        public string Word { get; set; }
        public Nullable<bool> Retrieve { get; set; }
    }
}

TutionCloudWeb/Models/Database/ShareAnArchivedTest.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutionCloudWeb.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareAnArchivedTest
    {
        public long ShareAnArchivedTestId { get; set; }
        public Nullable<long> WordId { get; set; }
        public Nullable<long> ExamId { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Password { get; set; }
        public string TestID { get; set; }
        public string LastName { get; set; }
        public string SentUserID { get; set; }
        public string Word { get; set; }
        public string Pronounciation { get; set; }
        public string Phrase { get; set; }
        public string Hint { get; set; }
        public string Definition { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> ShareOnline { get; set; }
        public string CreatedDate { get; set; }
        public string UpdatedDate { get; set; }
        public string CreatedOn { get; set; }
    }
}

TutionCloudWeb/Controllers/Wordutopia/SharingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TutionCloudWeb.Manager.Wordutopia;
using TutionCloudWeb.Model.Wordutopia;
using TutionCloudWeb.Models.Database;
using TutionCloudWeb.Models.Repository;

namespace TutionCloudWeb.Controllers.Wordutopia
{
    public class SharingController : BaseController
    {
        protected TutionCloudEntities TutionCloudEntities = new TutionCloudEntities();
        SharingManager SharingManager = new SharingManager();
        private userRepository _userRepo = new userRepository();
        public ActionResult Sharings()
        {
            return View();
        }
        public ActionResult CreateaWordListToShare()
        {
            var model = new TutionCloudWeb.Models.PostModel.OnlineCommunity.WordClass();
            //OnlineCommunityModel model = new OnlineCommunityModel();
            model.userId = _User.UserId;
            model.TestId = SharingManager.CreateWordListMaxId(_User.UserId.ToString());
            model.totalWordCount = TutionCloudEntities.SP_FETCH_USER_TOTAL_WORD_COUNT(model.userId, string.Empty).FirstOrDefault().ToString();
            return View(model);
            
        }
        [HttpGet]
        public JsonResult GetAllUserLists()
        {
            CreateAWordListToShareModel model = new CreateAWordListToShareModel();
            var results = TutionCloudEntities.tUsers.Select(x => new {x.Username, x.UserId}).ToList();
            var results2 = results.OrderBy(z => z.Username);
            return Json(results2, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult SortDropdownListBYCreateaWordListToShare(List<CreateAWordListToShareModel> model)
        {
            //List<CreateAWordListToShareModel> results = new List<CreateAWordListToShareModel>();
            //foreach (var a1 in model)
            //{
            //    CreateAWordListToShareModel CreateAWordListToShareModel = new CreateAWordListToShareModel();
            //    CreateAWordListToShareModel.UserID = a1.UserID;
            //    CreateAWordListToShareModel.UserName = a1.UserName;
            //    results.Add(CreateAWordListToShareModel);
            //}

            var results2 = model.OrderBy(z => z.UserName).ToList();
            return Json(results2, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult CreateaWordListToShareSendList(TutionCloudWeb.Models.PostModel.Word.AddFavouriteWord model)
        {
            var results = SharingManager.SendLIsts(model);

            return Json(results,JsonRequestBehavior.AllowGet); 
        }

        [HttpGet]
        public JsonResult UpdateaWordListToShareSendList(TutionCloudWeb.Models.PostModel.Word.AddFavouriteWord model)
        {
            var results = SharingManager.UpdateLIsts(model);

            return Json(results, JsonRequestBehavior.AllowGet);
        }

        public ActionResult WordListSharedwithMe()
        {
            var model = new TutionCloudWeb.Models.PostModel.OnlineCommunity.WordClass();            
            model.userId = _User.UserId;
            model.totalWordCount = TutionCloudEntities.SP_CreateAWordListToShare_COUNT(model.userId, string.Empty).FirstOrDefault().ToString();
            return View(model);
        }

        [HttpPost]
        public JsonResult ShareActivateCheckTestSharedWithMe(TutionCloudWeb.Models.PostModel.OnlineCommunity.WordClass model)
        {
            string a1 = model.userId.ToString();
            string asd = null;
            var results = _context.TestShareds.Where(

                            x => x.Password == model.Password &&

                            x.LastName == model.LastName &&

                            x.TestID == model.TestId &&

                            x.UserID == a1

                            ).FirstOrDefault();
            if (results != null)
            {
                DateTime sss = Convert.ToDateTime(results.CreatedOn);
                string dd = sss.ToString("dd");
                string MM = sss.ToString("MM");
                string yyyy = sss.ToString("yyyy");
                string hh = sss.ToString("hh");
                string mm = sss.ToString("mm");
                string tt = sss.ToString("tt");
                model.datestring = dd + "/" + MM + "/" + yyyy + " " + hh + ":" + mm + " " + tt;
                asd = sss.ToString("{0:dd/MM/yyyy hh:mm tt}");

                var Update = _context.TestShareds.Where(

                          x => x.Password == model.Password &&

                          x.LastName == model.LastName &&

                          x.TestID == model.TestId &&

                          x.UserID == a1

                          ).ToList();

                foreach (var a2 in Update)
                {
                    a2.Retrieve = true;
                    
                    _context.SaveChanges();
                }
            }
            else
            {
                model.datestring = "0";
            }

            

            return Json(model, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult ShareActivateCheck(TutionCloudWeb.Models.PostModel.OnlineCommunity.WordClass model)
        {
            string a1 = model.userId.ToString();
            var results = _context.CreateAWordListToShares.Where(

                            x => x.Password == model.Password &&

                            x.LastName == model.LastName &&

                            x.TestID == model.TestId &&

                            x.UserID == a1

                            ).FirstOrDefault();
            if (results != null)
            {
                DateTime sss = Convert.ToDateTime(results.CreatedOn);
                string dd = sss.ToString("dd");
                string MM = sss.ToString("MM");
                string yyyy = sss.ToString("yyyy");
                string hh = sss.ToString("hh");
                string mm = sss.ToString("mm");
                string tt = sss.ToString("tt");
                model.datestring = dd+"/"+MM+"/"+yyyy+" "+hh+":"+mm+" "+tt;
                string asd = sss.ToString("{0:dd/MM/yyyy hh:mm tt}");
                //model.datestring = sss.ToString("dd/MM/yyyy hh:mm tt");
            }
            else
            {
                model.datestring = "0";
            }

            var Update = _context.CreateAWordListToShares.Where(

                            x => x.Password == model.Password &&

                            x.LastName == model.LastName &&

                            x.TestID == model.TestId &&

                            x.UserID == a1

                            ).ToList();

            foreach (var a2 in Update)
            {
                a2.Retrieve = true;
                _context.SaveChanges();
            }
             

            return Json(model, JsonRequestBehavior.AllowGet);
        }



        [HttpPost]
        public JsonResult GetAllWordListSharedwithMe(SharingModel values)
        {
            CreateAWordListToShareModel model = new CreateAWordListToShareModel();
            var results = SharingManager.GetAllWordListSharedwithMe(values.CreatedOn);
            return Json(results,JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult GetCurrendItemWordListSharedwithMe(SharingModel values)
        {
            CreateAWordListToShareModel CreateAWordListToShareModel = new CreateAWordListToShareModel();
            var results =  TutionCloudEntities.CreateAWordListToShares.FirstOrDefault(i => i.CreatedOn == values.CreatedOn);
            
            CreateAWordListToShareModel.Password = results.Password;
            CreateAWordListToShareModel.TestID = results.TestID;
            CreateAWordListToShareModel.LastName = results.LastName;



            return Json(results, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Sharing_WordListSharedwithMeList(TutionCloudWeb.Models.PostModel.OnlineCommunity.WordList model)
        {
            return PartialView("~/Views/Sharing/_pv_Sharing_WordListSharedwithMe.cshtml", model);
        }

        [HttpPost]
        public ActionResult Sharing_Word_List_Pagination(TutionCloudWeb.Models.PostModel.OnlineCommunity.WordListPagination model)
        {
            return PartialView("~/Views/Wordutopia/_pv_Sharing_Word_List_Pagination.cshtml", model);
        }

        public JsonResult DeleteWordListSharedwithMe(string CreatedOn)
        {
            try
            {
                if (CreatedOn != null && CreatedOn != string.Empty)
                {
                    var results = TutionCloudEntities.DeleteCreateAWordLIstShare(CreatedOn);
                    return Json("1", JsonRequestBehavior.AllowGet);
                }
                else
                {

                    return Json("0", JsonRequestBehavior.AllowGet);
                }
            }
            catch(Exception ex){
                return Json("2", JsonRequestBehavior.AllowGet);
            }
            
        }
        public JsonResult DeleteALLWordListSharedwithMe(string userId)
        {
            try
            {
                if (userId != null && userId != string.Empty)
                {
                    var results = TutionCloudEntities.DeleteALLWordListSharedwithMe(userId);
                    return Json("1", JsonRequestBehavior.AllowGet);
                }
                else
                {

                    return Json("0", JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json("2", JsonRequestBehavior.AllowGet);
            }

        }
        //WordListSharedwithbyWords
        public ActionResult WordListSharedwithbyWords(string CreatedOn)
        {

TutionCloudWeb/Views/Sharing/ManageSharedTestStats.cshtml
@{
    ViewBag.Title = "ManageSharedTestStats";
    Layout = "~/Views/Shared/_Layout_Wordutopia_Home.cshtml";
}

   
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">




    <section class="manage_sec">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
                    <div class="heading">
                        <h6>Manage Shared Test Stats</h6>
                    </div>
                    <div class="newdrpn">
                        <div class="dropdown">
                            <button type="button" class="btn btn-primary " data-toggle="dropdown">Task Dropdown List <img src="~/Content/img/rightarrow.png" /></button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" onclick="history.back()">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
                    <div class="searching">
                        <p>Find summary result for any Shared Test</p>
                        <form class="inner_serach">
                            <div class="form_srches">
                                <div class="form-group">
                                    <label>Enter Password</label>
                                    <input type="text" class="form-control cust_textbx" id="txt_Password">
                                </div>
                                @*<span class="or">OR,</span>*@
                                <div class="form-group">
                                    <label>Test ID</label>
                                    <input type="text" class="form-control cust_textbx" id="txt_TestId">
                                </div>
                                <div class="form-group">
                                    <label>Enter TestName</label>
                                    <input type="text" class="form-control cust_textbx" id="txt_LastName">
                                </div>
                            </div>
                            <div class="bottom_srch">
                                <a href="#" class="btn sreach_button" id="a_btn_SharedTest"></a>
                            </div>
                        </form>
                    </div>

                    <div class="searching">
                        <p>Find All Test Stats for Specific Users</p>
                       
                        @using (Html.BeginForm("TestStatsForSpecificUsers", "Sharing", FormMethod.Post, new { @class = "inner_serach" }))
                        {
    @*<form class="inner_serach">*@
        <div class="form_srches">
            <div class="form-group">
                <label>Enter Username</label>
                @*<input type="text" class="form-control cust_textbx" placeholder="stewgem">*@
                @Html.TextBox("SearchName", null, new { @class = "form-control cust_textbx" })

                @*Html.TextBox("SearchString", new { @class="form-control cust_textbx", placeholder="stewgem"})*@
            </div>
        </div>
        <div class="bottom_srch">
            <a class="btn sreach_button" id="A_btn_SpecificUsers"></a>
            <input type="submit" id="btn_SpecificUsers" style="display:none;" value="submit" />
        </div>
    @*</form>*@
                        }
                       
                    </div>

                    <div class="searching">
                        <p>Find Stats for all Shared Test Words</p>
                        <form class="inner_serach">
                            <div class="form_srches">
                                <div class="form-group">
                                    <label>Enter a Test Word</label>
                                    <input type="text" class="form-control cust_textbx" placeholder="eclipse">
                                </div>
                            </div>
                            <div class="bottom_srch">
                                <a href="#" class="btn sreach_button"></a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>





    <!-- Bootstrap core JavaScript -->
   
    <script type="text/javascript">
        $(function () {
            $('#scrollToBottom1').bind("click", function () {
                $('html, body').animate({ scrollTop: ($('.Slider').offset().top + $('.Slider').height()) }, 1200);
                return false;
            });
           
        });
    </script>

<script>

    $("#A_btn_SpecificUsers").click(function () {
        $("#btn_SpecificUsers").click();
    });

    $("#a_btn_SharedTest").click(function () {

        var txt_Password = $("#txt_Password").val();
        var txt_TestId = $("#txt_TestId").val();
        var txt_LastName = $("#txt_LastName").val();

        var datas = new Object();
        datas.Password = txt_Password;
        datas.TestId = txt_TestId;
        datas.LastName = txt_LastName;

        $.ajax({
            type: "POST",
            url: "/Sharing/FindSummaryResultForAnySharedTest",
            data: datas,
            //contentType: "application/json; charset=utf-8",
            //dataType: "json",
            success: function (response) {
                if (response == 1) {
                    swal("RETRIEVE!", "Retrieve is successfully", "success");
                    setInterval(function () {
                        var url = "/Sharing/TestSharedWithMe/"
                        window.location(url);
                    }, 3000);
                }
                else {
                    toastrError('Retrieve is Failed');
                }
                
            },
            failure: function (response) {
                
            },
            error: function (response) {

            }
        });

    });
</script>

TutionCloudWeb/Views/Sharing/SetTestFormat.cshtml
@model TutionCloudWeb.Models.PostModel.Exam.CreateTest
@{
    ViewBag.Title = "CreateTest";
    Layout = "~/Views/Shared/_Layout_Wordutopia_Home.cshtml";
}
<style>
    .field-validation-error {
        color: red;
    }
</style>
<section class="Crt_formt">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="Tst_head">
                    <h6>Share a New Test</h6>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="Crt_tst_fomt">
                    <div class="newdrpn">
                        <div class="dropdown">
                            <button type="button" class="btn btn-primary " data-toggle="dropdown">Task Dropdown List <img src="~/Content/img/rightarrow.png" /></button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" onclick="history.back()">Back</a>
                                <a class="dropdown-item" id="A_AddSharedTestUsers">Add Shared Test Users</a>
                            </div>
                        </div>
                    </div>
                    <div class="Avg_scr">
                        <p>Average score to date: 87.2%</p>
                    </div>
                    <div class="outer_tst">
                        @using (Ajax.BeginForm("createtest", "Sharing", null, new AjaxOptions
        {
            HttpMethod = "POST",
            OnSuccess = "createtestSuccess",
            OnFailure = "createtestFailure",
        }, new { id = "tutioncloud-createtest" }))
                        {
                            @Html.ValidationSummary(true)
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(z => z.userId, new { Value = Model.userId })
                            @Html.HiddenFor(z => z.wordIds, new { Value = Model.wordIds })
                            <div class="test_form">
                                <h6>Test Details</h6>
                                <div class="form-group">
                                    <div class="form_al">
                                        <label>Test Title:</label>
                                        @*<input type="text" class="form-control" />*@
                                        @Html.TextBoxFor(m => m.title, new { autocomplete = "off", @class = "form-control" })
                                        @*@Html.ValidationMessageFor(model => model.title)*@
                                        <span id="error-title" style="display:none;" class="field-validation-error">required</span>
                                    </div>
                                </div>
                            </div>
                            <div class="test_frm">
                                <h6>Choose Test Format</h6>
                                <div class="form-group">
                                    <div class="form_al">
                                        <label>Overall Test Time (In Minutes):</label>
                                        @*<input type="text" class="form-control" />*@
                                        @Html.TextBoxFor(m => m.testTime, new { autocomplete = "off", @class = "form-control" })
                                        @*@Html.ValidationMessageFor(model => model.testTime)*@
                                        <span id="error-testTime" style="display:none;" class="field-validation-error">required</span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="form_al" style="text-align:center;font-weight:600;">
                                        OR
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="form_al">
                                        <label>Time per Word (In seconds):</label>
                                        @*<input type="text" class="form-control" />*@
                                        @Html.TextBoxFor(m => m.timePerWord, new { autocomplete = "off", @class = "form-control" })
                                        @*@Html.ValidationMessageFor(model => model.timePerWord)*@
                                        <span id="error-timePerWord" style="display:none;" class="field-validation-error">required</span>
                                    </div>
                                </div>

                            </div>
                            <div class="Bttn" style="display:none;">
                                <button type="submit" style="display:none;" id="btn-create-test" class="btn tst_btn">Start Test</button>
                                <button type="button" id="btn-dummy-create-test" class="btn tst_btn">Start Test</button>
                            </div>
                        }
                    </div>
                </div>
                <div class="lowerNav">
                    <nav class="navbar navbar-expand-sm  justify-content-center">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a href="https://en.wikipedia.org/wiki/Main.page" target="_blank">Wikipedia</a>
                            </li>
                            <li class="nav-item">
                                <a href=" https://www.google.com/search?q=calculator" target="_blank">Calculator</a>
                            </li>
                            <li class="nav-item">
                                <a href="https://www.google.com/maps/" target="_blank">Maps</a>
                            </li>
                            <li class="nav-item">
                                <a href="https://www.google.com/search?ei=DyM3XNbMEdH6kwW-lpLgCA&q=google+currency+converter&oq=google+currency+converter&gs_l=psy-ab.3..35i39j0i7i30l2j0j0i7i30j0j0i7i30j0l3.211.5629..6378...0.0..0.282.1593.0j6j3......0....1..gws-wiz.......0i71j0i30j0i131i67j35i304i39.BbyIqE0P5UY" target="_blank">Currency Converter</a>
                            </li>
                            <li class="nav-item">
                                <a href="https://www.timeanddate.com/worldclock/full.html" target="_blank">World Clocks</a>
                            </li>
                            <li class="nav-item">
                                <a href="https://translate.google.com/" target="_blank">Translator</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>


<script>
    $("#a_ClickSharing").css({ "color": "#98aaff" });
    $(document).on('click', '#btn-dummy-create-test', function () {
        var title = $('#title').val();
        var testTime = $('#testTime').val();
        var timePerWord = $('#timePerWord').val();
        if (title != "" && title != null) {
            $('#error-title').hide();
            if ((testTime != "" && testTime != null) || (timePerWord != "" && timePerWord != null)) {
                $('#error-timePerWord').hide();
                $('#error-testTime').hide();
                $('#btn-create-test').trigger('click');
            }
            else {
                if ((testTime == "" || testTime == null) && (timePerWord == "" || timePerWord == null)) {
                    $('#error-timePerWord').show();
                    $('#error-testTime').show();
                }
            }
        }
        else {
            $('#error-title').show();
            if ((testTime != "" && testTime != null) || (timePerWord != "" && timePerWord != null)) {
                $('#error-timePerWord').hide();
                $('#error-testTime').hide();
            }
            else {
                if ((testTime == "" || testTime == null) && (timePerWord == "" || timePerWord == null)) {
                    $('#error-timePerWord').show();
                    $('#error-testTime').show();
                }
            }
        }
    });

</script>


<script>
    $(document).on('keypress', "#testTime , #timePerWord", function (e) {
        //if the letter is not digit then display error and don't type anything
        if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
            //display error message
            //$("#errmsg").html("Digits Only").show().fadeOut("slow");
            return false;
        }
    });
</script>

<script>
    $("#A_AddSharedTestUsers").click(function () {
        $("#btn-create-test").click();
    });


    function createtestFailure(data) {
        toastrError(data.message);
    }

    function createtestSuccess(data) {
        if (data.status) {
            toastrSuccess("Exam created")
            setTimeout(function () {
                var encodedString = btoa(data.id);
                window.location.href = "/Sharing/AddSharedTestUsers/" + encodedString;
            }, 400);
        }
        else {
            toastrError(data.message);
        }
    }

</script>

TutionCloudWeb/Views/Sharing/Sharings.cshtml
@{
    ViewBag.Title = "Sharings";
    Layout = "~/Views/Shared/_Layout_Wordutopia_Home.cshtml";
}

<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="heading_share">
                    <h6>Share Word Lists & Tests</h6>
                </div>
                <div class="TstSHare">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            <div class="innerleft">
                                <img src="~/Content/img/folderplus.jpg" /><a href="/Sharing/CreateaWordListToShare/" class="Share_action">Create a Word List To Share</a>
                            </div>
                            <div class="innerleft">
                                <img src="~/Content/img/folderShare.png" /><a href="/Sharing/WordListSharedbyMe/" class="Share_action">Word Lists Shared by Me</a>
                            </div>
                            <div class="innerleft">
                                <img src="~/Content/img/folderShare.png" /><a href="/Sharing/WordListSharedwithMe/" class="Share_action">Word Lists Shared with Me</a>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            <div class="innerShare">
                                <img src="~/Content/img/shareicon.png" /><a href="/Sharing/CreateaNewTesttoShare/" class="Share_action">Create a New Test to Share</a>
                            </div>
                            <div class="innerShare">
                                <img src="~/Content/img/shareicon.png" /><a href="/Sharing/ShareanArchivedTest/" class="Share_action">Share an Archived Test</a>
                            </div>
                            <div class="innerShare">
                                <img src="~/Content/img/shareicon.png" /><a href="/Sharing/TestSharedbyMe/" class="Share_action">Tests Shared by Me</a>
                            </div>
                            <div class="innerShare">
                                <img src="~/Content/img/shareicon.png" /><a href="/Sharing/TestSharedWithMe/" class="Share_action">Tests Shared With Me</a>
                            </div>
                            <div class="innerShare">
                                <img src="~/Content/img/shareicon.png" /><a href="/Sharing/ManageSharedTestStats/" class="Share_action">Manage Shared Test Stats</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    $("#a_ClickSharing").css({ "color": "#98aaff" });
</script>